# Site Info
title: What a fucking day.
tagline: ''
description: 'What a fucking day.'
baseurl: ""
url: https://cadeeper.github.io
logo: '/public/logo.png'

# Site configurations
#plugins: [jekyll-paginate-v2]
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
#pagination:
#  enabled: true
#  per_page: 5
#  permalink: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: nut
  description: 一个热爱开发的非科班生
  gravatar: da97f3f20fa16c99ddced97536ea4361 # md5 hash of your email address
  contact:
    # linkedin:  <hide>
    github:    https://github.com/cadeeper
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    email:     mailto:cadeeper@gmail.com

# Navigation (2nd level links supported)
nav:
  首页:
    - '/'
  文章:
    - '/blog/'
    - { 分类: '/blog/categories/' }
    - { 标签: '/blog/tags/' }
  与我相关:
    - '/about/'
  #Github Project:
  #  - 'http://github.com/cadeeper'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'cadeeper' # leave blank if you don't want disqus

